---
name: Class-Plugin-Util
version: 0.003
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Utility functions for supporting Plug-ins.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Params::Util: 0.22
  UNIVERSAL::require: 0.1
build_requires:
  Test::Simple: 0.42
recommends:
  Perl::Critic: 1.051
  Pod::Coverage: 0.18
  Test::Exception: 0.25
  Test::Kwalitee: 0.3
  Test::Perl::Critic: 1
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
  Test::YAML::Meta: 0.04
dynamic_config: 0
provides:
  Class::Plugin::Util:
    file: lib/Class/Plugin/Util.pm
    version: 0.003
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: Module
