---
name: Class-Plugin-Util
version: 0.005
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Utility functions for supporting Plug-ins.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Simple: 0.42
dynamic_config: 0
provides:
  Class::Plugin::Util:
    file: lib/Class/Plugin/Util.pm
    version: 0.005
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: Module
